using Core;

namespace Domain;

[AutoGeneratedKey]
public class ActionStatus : GuidEntity
{
    protected ActionStatus() { }

    public ActionStatus(Status status)
    {
        Status = status;
    }

    public Status Status { get; set; }
}