using Core;

namespace Domain;

[AutoGeneratedKey]
public class ActionComment : GuidEntity
{
    protected ActionComment() { }

    public ActionComment(string value)
    {
        Value = value;
    }

    public string Value { get; set; }
}