using Core;

namespace Domain;

[AutoGeneratedKey]
public class MonthlyStatus : GuidEntity
{
    protected MonthlyStatus() { }

    public MonthlyStatus(Month month, Status status)
    {
        //Year = year;
        Month= month;
        Status = status;
    }
    //public int Year { get; set; }
    public Month Month { get; set; }
    public Status Status { get; set; }
}