using Core;

namespace Domain;

[AutoGeneratedKey]
public class ParticipantConsultant : GuidEntity
{
    protected ParticipantConsultant() { }

    public ParticipantConsultant(Guid consultantId, ConsultantPermission permission, UserValue assignedBy = null)
    {
        ConsultantId = consultantId;
        LastEdit = DateTime.Now;
    }
    public Guid ConsultantId { get; set; }
    public DateTime LastEdit { get; set; }
    public ConsultantPermission Permission { get; set; }
    public UserValue AssignedBy { get; set; }
}

