using Core;

namespace Domain;

[AutoGeneratedKey]
public class Year : GuidEntity
{
    protected Year() { }

    public Year(int value, YearMonth start, YearMonth end)
    {
        Value = value;
        Start= start;
        End= end;
    }
    
    [IdentifierKey]
    public long Key { get; set; }
    public int Value { get; set; }
    public YearMonth Start{ get; set; }
    public YearMonth End{ get; set; }
}