
namespace Core;

[AttributeUsage(AttributeTargets.Property)]
public sealed class CalculatedAttribute : Attribute {}


[AttributeUsage(AttributeTargets.Property)]
public sealed class IsUniqueAttribute : Attribute { }


[AttributeUsage(AttributeTargets.Property)]
public class PrimaryKeyAttribute : Attribute {}


[AttributeUsage(AttributeTargets.Property)]
public class IdentifierKeyAttribute : Attribute { }


[AttributeUsage(AttributeTargets.Property)]
public sealed class ImmutableAttribute : Attribute {}


[AttributeUsage(AttributeTargets.Class)]
public class AutoGeneratedKeyAttribute : Attribute {}


[AttributeUsage(AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Method | AttributeTargets.Parameter)]
public class DateOnlyAttribute : Attribute {}