using Core;

namespace Domain
{
    public abstract class NewsContent : LongEntity
    {
	    public abstract string MainImage { get; }
	}


	public class TopImageContent : NewsContent
    {
        public string Image { get; set; }
        public string Text { get; set; }

        public override string MainImage => Image;
    }
	public class BottomImageContent : NewsContent
    {
        public string Image { get; set; }
        public string Text { get; set; }
        public override string MainImage => Image;
	}
	public class TopBottomImageContent : NewsContent
    {
        public string TopImage { get; set; }
        public string BottomImage { get; set; }
        public string Text { get; set; }
        public override string MainImage => TopImage;
	}
/*	public class FreeNewsContent : NewsContent
    {
	    public string Content { get; set; }

	    public override string MainImage => Files.Any() ? Files.First().FileName : null;
	}*/
	public class SliderImagesContent : NewsContent
    {
	    protected SliderImagesContent()
	    {
				
	    }
	    public SliderImagesContent(string text, IEnumerable<SliderImageItem> imageItems)
	    {
		    Text = text;
		    var first = imageItems.First();
		    first.OrderRank = 2.5;
		    SliderImageItems = new List<SliderImageItem>{first};

		    foreach (var item in imageItems.Where(i => i.Image != first.Image).ToList())
			    AddImage(item);
	    }

	    public string Text { get; set; }
	    public override string MainImage => SliderImageItems.FirstOrDefault()?.Image;
	    public virtual ICollection<SliderImageItem> SliderImageItems { get; set; }


	    public void AddImage(SliderImageItem item)
	    {
			item.SortAsLast(SliderImageItems.OrderBy(i=>i.OrderRank).Last());
	    }
	}


	public class ContentFile : GuidEntity
    {
	    public string FileName { get; set; }
    }

    [AutoGeneratedKey]
	public class SliderImageItem : GuidEntity, ISortable,IEntity
	{
		public string Image { get; set; }
		public string Title { get; set; }
		public string Description { get; set; }
		public double OrderRank { get; set; }
	}
}
