using Core;

namespace Domain;

[AutoGeneratedKey]
public class Person: GuidEntity
{
    protected Person() { }

    public Person(UserValue user, PersonRole role) 
    {
        User = user;
        Role = role;
    }
    public UserValue User { get; set; }
    public PersonRole Role{ get; set; }
}

