using Core;

namespace Domain;

[AutoGeneratedKey]
public class Consultant : Aggregate
{
    protected Consultant() { }
    public Consultant(UserValue user)
    {
        User = user;
    }

    public UserValue User { get; set; }
    public string PicProfile { get; set; }
}

