using Core;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Core.Domain;

namespace Domain
{
	[AutoGeneratedKey]
	public class Announcement : Aggregate, IHaveAccess
	{
		public Announcement()
		{
				
		}

		public Announcement(string title, string header, string image, string description, ICollection<AnnouncementFile> files)
		{
			Title = title;
            Header = header;
            Image = image;
			Description = description;
			Files = files;
		}

		public string Title { get; set; }
        public string Header { get; set; }
        public string Image { get; set; }
		public string Description { get; set; }
        public string TitleImage { get; set; }
        public bool IsPublished { get; set; }
        public bool IsActive { get; set; }
        public bool IsArchived { get; set; }
        public DateTime? ExpirationTime { get; set; }
        public int ExpireDuration { get; set; }
        public Guid OwnerScopeId { get; set; }
        public bool ShouldAuthenticated { get; set; }
        public virtual ICollection<AnnouncementFile> Files { get; set; }
        public bool IsGlobal { get; set; }
        public virtual ICollection<AccessEntityValue> AccessEntityItems { get; set; }
    }
}
