using Core;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Domain
{
	[AutoGeneratedKey]
	public class Announcement : LongAggregate
	{
		public Announcement()
		{
				
		}

		public Announcement(string title, string image, string description, ICollection<AnnouncementFiles> files)
		{
			Title = title;
			Image = image;
			Description = description;
			Files = files;
		}

		public string Title { get; set; }
		public string Image { get; set; }
		public string Description { get; set; }
		public virtual ICollection<AnnouncementFiles> Files { get; set; }
	}
}
