using Core;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Domain
{
	[AutoGeneratedKey]
	public class AnnouncementFiles : GuidEntity
	{
		public string FilesName { get; set; }
		public virtual Announcement Announcement{ get; set; }
	}
}
