using Core;
using Shared.Types;

namespace Domain
{
	[AutoGeneratedKey]
	public class AnnouncementFile : GuidEntity
	{
		public string Title { get; set; }
        public AttachedFile File{ get; set; }
    }
}
